global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-score-service'
    static_configs:
      - targets: ['host.docker.internal:8000']
    rule_files:
    - "alert.rules.yml"
